PDC_TGbots/PDC_TGBOTS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("home.urls")),
    path("help/", include("help.urls")),
    path("users/", include("users.urls")),
    path("order-a-bot/", include("order.urls")),
    path("team/", include("team.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("admin-chat/", include("adminchat.urls")),
    path("all-requests/", include("all_requets.urls")),
    path('support/', include("support.urls")),
    path('statistic/', include("statistic.urls")),
    path('administration/', admin.site.urls),
]

handler404 = "PDC_TGBOTS.views.page_not_found_view"
handler500 = "PDC_TGBOTS.views._handler500"

PDC_TGbots/help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("what-i-must-doing-if-i-dont-know-hard", views.WhatIMustDoingIfIDontKnowHard.as_view()),
    path("how-be-admin", views.HowBeAdmin.as_view()),
    path("how-see-my-order", views.HowSeeMyOrder.as_view()),
    path("why-i-go-to-notpage", views.WhyIGoToNotPage.as_view()),
]

PDC_TGbots/order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("my-orders", views.MyOrders.as_view(), name="my-orders"),
    path("<int:order_id>", views.Detail.as_view(), name="detial"),
    path("<int:order_id>/leave-message", views.LeaveMessage.as_view(), name="leave_message"),
    path("leave-order", views.LeaveOrder.as_view(), name="leave_order"),
    path("<int:_order>/cancel", views.Cancel.as_view(), name="cancel"),
    path("<int:_order>/set_code", views.SetCode.as_view(), name="set_code"),
    path("<int:_order>/buy", views.Buy.as_view(), name="buy"),
    path("<int:_order>/set_price", views.SetPrice.as_view(), name="set_price"),
    path("<int:_order>/download", views.DownloadCode.as_view(), name="download")
]

PDC_TGbots/templates/my_orders/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/style.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <title>PTC-bots</title>
    <style>
        .center {
            display: block;
            min-width: 30vw;
            max-width: 60vw;
            margin-top: 0.5em;
            margin-left: auto; 
            margin-right: auto
        }
    </style>
</head>
<body>
    <img class="center" src="https://staticfiles-com.netlify.app/static/img/ZIP.png">
    {% if request.user.lang == "russian" %}
        <a class="btn btn-outline-primary center" href="{{order.code}}">Скачать</a>
    {% elif request.user.lang == "english" %}
        <a class="btn btn-outline-primary center" download="{{order.code}}">Download</a>
    {% endif %}
</body>
</html>

PDC_TGbots/templates/my_orders/index.html
{% extends 'base.html' %}

{% block title%}PTC bots - Мои заказы{% endblock %}

{% block content %}
    <div class="container my-5">
        {% if request.user.lang == "russian" %}
            {% if no_list %}
                <h2 style="text-align: center; margin-top: 1em;">Неготовые Заказы</h2>
                <hr style="color: black;">
                <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 g-4">
                    {% for order in no_list %}
                        <div class="col">
                            <div class="card">
                                {% if order.power == "Сложность: лёгкая" %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_easy.png" class="card-img-top" alt="image">
                                {% elif order.power == "Сложность: средняя" %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_medium.png" class="card-img-top" alt="image">
                                {% else %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_hard.png" class="card-img-top" alt="image">
                                {% endif %}
                                <hr>
                                <div class="card-body">
                                <h5 class="card-title">{{order.order_title}}</h5>
                                <p class="card-text">{{order.order_date}}</p>
                                <a style="display: block; margin: auto;" class="btn btn-outline-primary" href="{% url 'order:detial' order.id %}">
                                    Перейти
                                </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% elif yes_list %}
                <h2 style="text-align: center; margin-top: 1em;">Готовые Заказы</h2>
                <hr style="color: black;">
                <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 g-4">
                    {% for order in yes_list %}
                        <div class="col">
                            <div class="card">
                                {% if order.power == "Сложность: лёгкая" %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_easy.png" class="card-img-top" alt="image">
                                {% elif order.power == "Сложность: средняя" %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_medium.png" class="card-img-top" alt="image">
                                {% else %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_hard.png" class="card-img-top" alt="image">
                                {% endif %}
                                <hr>
                                <div class="card-body">
                                <h5 class="card-title">{{order.order_title}}</h5>
                                <p class="card-text">{{order.order_date}}</p>
                                <a style="display: block; margin: auto;" class="btn btn-outline-primary" href="{% url 'order:detial' order.id %}">
                                    Перейти
                                </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h2 style="text-align: center;">У вас нет заказов</h2>
            {% endif %}
            {% if ready_list %}
                <h2 style="text-align: center; margin-top: 1em;">Оплаченые заказы</h2>
                <hr style="color: black;">
                <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 g-4">
                    {% for order in ready_list %}
                        <div class="col">
                            <div class="card">
                                {% if order.power == "Сложность: лёгкая" %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_easy.png" class="card-img-top" alt="image">
                                {% elif order.power == "Сложность: средняя" %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_medium.png" class="card-img-top" alt="image">
                                {% else %}
                                    <img src="https://staticfiles-com.netlify.app/static/img/bot_hard.png" class="card-img-top" alt="image">
                                {% endif %}
                                <hr>
                                <div class="card-body">
                                <h5 class="card-title">{{order.order_title}}</h5>
                                <p class="card-text">{{order.order_date}}</p>
                                <a style="display: block; margin: auto;" class="btn btn-outline-primary" href="{% url 'order:detial' order.id %}">
                                    Перейти
                                </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% elif request.user.lang == "english" %}
        {% if no_list %}
        <h2 style="text-align: center; margin-top: 1em;">Unfinished Orders</h2>
        <hr style="color: black;">
        <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 g-4">
            {% for order in no_list %}
                <div class="col">
                    <div class="card">
                        {% if order.power == "Сложность: лёгкая" %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_easy.png" class="card-img-top" alt="image">
                        {% elif order.power == "Сложность: средняя" %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_medium.png" class="card-img-top" alt="image">
                        {% else %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_hard.png" class="card-img-top" alt="image">
                        {% endif %}
                        <hr>
                        <div class="card-body">
                        <h5 class="card-title">{{order.order_title}}</h5>
                        <p class="card-text">{{order.order_date}}</p>
                        <a style="display: block; margin: auto;" class="btn btn-outline-primary" href="{% url 'order:detial' order.id %}">
                            Go
                        </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% elif yes_list %}
        <h2 style="text-align: center; margin-top: 1em;">Finished Orders</h2>
        <hr style="color: black;">
        <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 g-4">
            {% for order in yes_list %}
                <div class="col">
                    <div class="card">
                        {% if order.power == "Сложность: лёгкая" %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_easy.png" class="card-img-top" alt="image">
                        {% elif order.power == "Сложность: средняя" %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_medium.png" class="card-img-top" alt="image">
                        {% else %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_hard.png" class="card-img-top" alt="image">
                        {% endif %}
                        <hr>
                        <div class="card-body">
                        <h5 class="card-title">{{order.order_title}}</h5>
                        <p class="card-text">{{order.order_date}}</p>
                        <a style="display: block; margin: auto;" class="btn btn-outline-primary" href="{% url 'order:detial' order.id %}">
                            Go
                        </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h2 style="text-align: center;">You have no orders</h2>
    {% endif %}
    {% if ready_list %}
        <h2 style="text-align: center; margin-top: 1em;">Paid orders</h2>
        <hr style="color: black;">
        <div class="row row-cols-1 row-cols-md-1 row-cols-lg-2 g-4">
            {% for order in ready_list %}
                <div class="col">
                    <div class="card">
                        {% if order.power == "Сложность: лёгкая" %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_easy.png" class="card-img-top" alt="image">
                        {% elif order.power == "Сложность: средняя" %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_medium.png" class="card-img-top" alt="image">
                        {% else %}
                            <img src="https://staticfiles-com.netlify.app/static/img/bot_hard.png" class="card-img-top" alt="image">
                        {% endif %}
                        <hr>
                        <div class="card-body">
                        <h5 class="card-title">{{order.order_title}}</h5>
                        <p class="card-text">{{order.order_date}}</p>
                        <a style="display: block; margin: auto;" class="btn btn-outline-primary" href="{% url 'order:detial' order.id %}">
                            Go
                        </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
        {% endif %}
    </div>
{% endblock %}