PDC_TGbots/PDC_TGBOTS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("home.urls")),
    path("help/", include("help.urls")),
    path("users/", include("users.urls")),
    path("order-a-bot/", include("order.urls")),
    path("team/", include("team.urls")),
    path("grappelli/", include("grappelli.urls")),
    path("admin-chat/", include("adminchat.urls")),
    path("all-requests/", include("all_requets.urls")),
    path('support/', include("support.urls")),
    path('statistic/', include("statistic.urls")),
    path('administration/', admin.site.urls),
]

handler404 = "PDC_TGBOTS.views.page_not_found_view"
handler500 = "PDC_TGBOTS.views._handler500"

PDC_TGbots/help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("what-i-must-doing-if-i-dont-know-hard", views.WhatIMustDoingIfIDontKnowHard.as_view()),
    path("how-be-admin", views.HowBeAdmin.as_view()),
    path("how-see-my-order", views.HowSeeMyOrder.as_view()),
    path("why-i-go-to-notpage", views.WhyIGoToNotPage.as_view()),
]

PDC_TGbots/home/urls.py
from django.urls import path
from . import views

appname = "home"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("close-language-message", views.CloseLanguageMessage.as_view(), name="close-lang-message"),
    path("change-language/<str:language>", views.ChangeLanguage.as_view(), name="change-language"),
    path("account/", views.Account.as_view(), name="my-account"),
    path("shop/", views.Shop.as_view(), name="shop"),
    path("shop/buy/<int:coins>", views.Buy.as_view(), name="buy"),
    path("problems", views.MyProblems.as_view(), name="my_problems"),
]

PDC_TGbots/order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("my-orders", views.MyOrders.as_view(), name="my-orders"),
    path("<int:order_id>", views.Detail.as_view(), name="detial"),
    path("<int:order_id>/leave-message", views.LeaveMessage.as_view(), name="leave_message"),
    path("leave-order", views.LeaveOrder.as_view(), name="leave_order"),
    path("<int:_order>/cancel", views.Cancel.as_view(), name="cancel"),
    path("<int:_order>/set_code", views.SetCode.as_view(), name="set_code"),
    path("<int:_order>/buy", views.Buy.as_view(), name="buy"),
    path("<int:_order>/set_price", views.SetPrice.as_view(), name="set_price"),
    path("<int:_order>/download", views.DownloadCode.as_view(), name="download")
]

PDC_TGbots/home/models.py
from django.db import models

# Create your models here.

PDC_TGbots/home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView
from users.models import User
from order.models import Order

class Index(TemplateView):
    template_name = "home/index.html"

class Account(View):
    def get(self, request):
        if request.user.is_authenticated:
            day, week, all_orders = 0, 0, 0
            orders_list_day = []
            orders_list_week = []
            for order in Order.objects.all():
                if order.is_new_day():
                    orders_list_day.append(order)
            for order in Order.objects.all():
                if order.is_new_week():
                    orders_list_week.append(order)
            for order in orders_list_day:
                if order.user == request.user:
                    day += 1
            for order in orders_list_week:
                if order.user == request.user:
                    week += 1
            for order in Order.objects.all():
                if order.user == request.user:
                    all_orders += 1
            return render(request, "account/index.html", {
                    "username": request.user.username.title(), 
                    "all_orders": all_orders,
                    "day": day,
                    "week": week
                }
            )
        else:
            return redirect("/")

class Shop(View):
    def get(self, request):
        if request.user.is_authenticated:
            return render(request, "shop/index.html")
        else:
            return redirect("/")



class Buy(View):
    def get(self, request, coins):
        if request.user.is_authenticated:
            request.user.coins += coins
            request.user.save()
            return redirect("/shop/")
        else:
            return redirect("/")

class MyProblems(View):
    def get(self, request):
        if request.user.is_authenticated:
            if request.user.is_admin():
                return render(request, "problems/index.html")
            else:
                return render(request, "not.html", {"message": "Скорее всего вы не являетесь администратором..."})
        else:
            return redirect("/")

class CloseLanguageMessage(View):
    def get(self, request):
        if request.user.is_authenticated:
            request.user.lang_has_changed = True
            request.user.save()
        return redirect("/")

class ChangeLanguage(View):
    def get(self, request, language):
        if request.user.is_authenticated:
            request.user.lang = language
            request.user.lang_has_changed = True
            request.user.save()
        return redirect("/")

PDC_TGbots/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="container my-5">
            {% if request.user.lang == "russian" %}
                <p class="title-title-page-home" style="font-size: 250%; text-align: center;">Здравствуйте, {{request.user.username.title}}</p>
                {% if request.user.is_admin == False %}
                    <div style="font-size: 200%; text-align: center; margin-top: 0.5em;">
                        <p><a href="{% url 'order:index' %}">Заказать бота</a></p>
                        <p><a href="/order-a-bot/my-orders">Мои заказы</a></p>
                        <p><a href="/account">Мой аккаунт</a></p>
                    </div>
                {% else %}
                    <div style="font-size: 200%; text-align: center; margin-top: 0.5em;">
                        <p>
                            <a href="/support/">Ответить как тех-поддержка</a>
                        </p>
                        <p>
                        <a href="{% url 'order:my-orders' %}">Все заказы</a>
                        </p>
                        <p>
                            <a href="/account">Мой аккаунт</a>
                        </p>
                    </div>
                {% endif %}
            {% elif request.user.lang == "english" %}
                <p class="title-title-page-home" style="font-size: 250%; text-align: center;">Hello, {{request.user.username.title}}</p>
                {% if request.user.is_admin == False %}
                    <div style="font-size: 200%; text-align: center; margin-top: 0.5em;">
                        <p><a href="{% url 'order:index' %}">Order a bot</a></p>
                        <p><a href="/order-a-bot/my-orders">My orders</a></p>
                        <p><a href="/account">My account</a></p>
                    </div>
                {% else %}
                    <div style="font-size: 200%; text-align: center; margin-top: 0.5em;">
                        <p>
                            <a href="/support/">Reply as tech support</a>
                        </p>
                        <p>
                        <a href="{% url 'order:my-orders' %}">All orders</a>
                        </p>
                        <p>
                            <a href="/account">My account</a>
                        </p>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    {% else %}
      <div class="elem-content">
        <h1 class="title-title">PDC-TGbots <img src="https://staticfiles-com.netlify.app/static/img/navicon.png" width="45" height="45" alt=""></h1>
        <div class="content-text">
          <h3 class="text-text">PDC-TGbots: The best TeleBot development service!</h3>
          <p><h3 class="text-text">Convenient order tracking system!</h3></p>
          <p><h3 class="text-text">Fast administration system and solution to any problem!</h3></p>
          <p><h3 class="text-text">The best prices!</h3></p>
        </div>
        <div class="links-dev">
            <p><a style="width: 95%;" class="btn btn-outline-success" href="/users/register">Register</a></p>
            <p><a style="width: 95%;" class="btn btn-outline-primary" href="/users/login">Sign in</a></p>
        </div>
      </div>
    {% endif %}
{% endblock %}